name: Runner Workflow


on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: read


jobs:
  commit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Commit
      run: |
        mkdir -p vaults
        echo "test" > vaults/vault.txt
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add vaults/*
        git commit -m "Add new vault files"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
